---
abstract: 'OpenID credential for Catalyst::Plugin::Authentication framework.'
author:
  - 'Ashley Pond V <ashley.org>'
build_requires:
  IO::Socket::INET: 0
  LWPx::ParanoidAgent: 1.03
  Net::DNS: 0
  Net::OpenID::Server: 1.02
  Test::More: 0.42
  Test::WWW::Mechanize: 1.20
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authentication-Credential-OpenID
no_index:
  directory:
    - inc
    - t
recommends:
  Config::General: 2
  LWPx::ParanoidAgent: 1.03
  Math::BigInt: 0
  YAML: 0.6
requires:
  Cache::FastMmap: 1.28
  Catalyst: 5.7
  Catalyst::Authentication::User::Hash: 0
  Catalyst::Devel: 1
  Catalyst::Engine::HTTP: 0
  Catalyst::Plugin::Session::State::Cookie: 0.08
  Catalyst::Plugin::Session::Store::FastMmap: 0.05
  Class::Accessor::Fast: 0
  Crypt::DH: 0.05
  HTML::Parser: 3
  LWP::UserAgent: 0
  Net::OpenID::Consumer: 1.03
  parent: 0.2
version: 0.13
