--- 
abstract: OpenID credential for Catalyst::Authentication framework.
author: 
  - ", Ashley Pond V C<< <ashley@cpan.org> >>. Some of"
build_requires: 
  Catalyst::Plugin::Session::Store::FastMmap: 0
  LWP::UserAgent: 0
  Net::OpenID::Server: 0
  Test::More: 0.42
  Test::WWW::Mechanize: 1.20
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authentication-Credential-OpenID
no_index: 
  directory: 
    - inc
    - t
recommends: 
  LWPx::ParanoidAgent: 1.03
  Math::BigInt: 0
requires: 
  Catalyst::Authentication::User::Hash: 0
  Catalyst::Exception: 0
  Catalyst::Runtime: 5.7
  Class::Accessor::Fast: 0
  Crypt::DH: 0.05
  Net::OpenID::Consumer: 0.14
  UNIVERSAL::require: 0
version: 0.01
